"""The add-on icon.

A single PNG in ``icons/`` is loaded into a preview collection (the standard way
to get a custom icon into panels and menus) and used via ``icon_value``.  Menus
entries accept ``icon_value``; *submenu buttons* only accept built-in icon names,
so the Add-menu entry itself falls back to ``CAMERA_DATA``.

The mark is an original drawing (three coloured arcs around a fisheye lens,
generated by ``scripts/make_icon.py``) - it is *not* the OpenCV logo, which is a
trademark of the OpenCV project.
"""

from __future__ import annotations

import os
from typing import Optional

import bpy

from ..core import paths

ICON_NAME = "visionsim"
ICON_FILENAME = "visionsim.png"
#: built-in icon used when the PNG cannot be loaded
FALLBACK_ICON = "CAMERA_DATA"

_collection: Optional[bpy.types.PreviewCollection] = None


def icon_path() -> str:
    return os.path.join(paths.ADDON_ROOT, "icons", ICON_FILENAME)


def icon_id() -> int:
    """Icon id for ``icon_value``, or ``0`` when the icon is unavailable.

    Blender only assigns a real icon id once a UI exists; in background mode the
    id stays ``0`` (no icon), which is why callers fall back to a built-in icon.
    """
    if _collection is None:
        return 0
    preview = _collection.get(ICON_NAME)
    return preview.icon_id if preview is not None else -1


def operator(layout, idname: str, text: str = "", fallback_icon: str = FALLBACK_ICON, **props):
    """``layout.operator`` with the custom icon (and a built-in fallback)."""
    value = icon_id()
    kwargs = {"text": text}
    if value > 0:
        kwargs["icon_value"] = value
    else:
        kwargs["icon"] = fallback_icon
    operator = layout.operator(idname, **kwargs)
    for name, prop in props.items():
        setattr(operator, name, prop)
    return operator


def is_loaded() -> bool:
    """True when the icon file was loaded into a preview collection."""
    return _collection is not None and ICON_NAME in _collection


def register() -> None:
    global _collection
    if _collection is None:
        import bpy.utils.previews  # lazily available submodule
        _collection = bpy.utils.previews.new()
    path = icon_path()
    if os.path.exists(path) and ICON_NAME not in _collection:
        try:
            _collection.load(ICON_NAME, path, "IMAGE")
        except (RuntimeError, TypeError):
            pass


def unregister() -> None:
    global _collection
    if _collection is not None:
        bpy.utils.previews.remove(_collection)
        _collection = None