"""The add-on icon set.

One monochrome line PNG per menu entry in ``icons/`` (generated by
``scripts/make_icon.py``).  Blender loads them into a preview collection and they
are used through ``icon_value``; the entries of :menuselection:`Add ▸ VisionSim`
each get their own mark, so the entries can be told apart at menu size.

Blender only assigns real icon ids once a UI exists: in background mode ids are
``0`` (no icon), which is why every call site has a built-in fallback.  The marks
are original; do not ship the OpenCV logo (a trademark of the OpenCV project).
"""

from __future__ import annotations

import os
from typing import Dict, List, Optional

import bpy

from ..core import paths

#: icon name -> built-in fallback (used when our PNG cannot be shown)
FALLBACKS: Dict[str, str] = {
    "visionsim": "TRACKING",
    "camera": "CAMERA_DATA",
    "fisheye": "CAMERA_DATA",
    "brown_conrady": "CAMERA_DATA",
    "rational": "CAMERA_DATA",
    "pinhole": "CAMERA_DATA",
    "camera_scene": "MESH_CUBE",
    "avm_scene": "MESH_PLANE",
    "drive_scene": "PLAY",
    "road_scene": "FORWARD",
}

_collection: Optional[object] = None


def icons_dir() -> str:
    return os.path.join(paths.ADDON_ROOT, "icons")


def icon_path(name: str) -> str:
    return os.path.join(icons_dir(), f"{name}.png")


def available() -> List[str]:
    try:
        return sorted(
            name[:-4] for name in os.listdir(icons_dir()) if name.endswith(".png")
        )
    except OSError:
        return []


def icon_id(name: str = "visionsim") -> int:
    """Icon id for ``icon_value``, or ``0`` when unavailable (no UI, load error)."""
    if _collection is None:
        return 0
    preview = _collection.get(name)
    return preview.icon_id if preview is not None else 0


def is_loaded(name: str = "visionsim") -> bool:
    return _collection is not None and name in _collection


def kwargs(name: str = "visionsim", text: str = "") -> dict:
    """Keyword arguments for ``layout.operator`` / ``layout.menu``."""
    value = icon_id(name)
    if value > 0:
        result = {"icon_value": value}
    else:
        result = {"icon": FALLBACKS.get(name, "NONE")}
    if text:
        result["text"] = text
    return result


def operator(layout, idname: str, text: str = "", name: str = "visionsim", **props):
    """``layout.operator`` with the icon of ``name`` (built-in fallback)."""
    operator = layout.operator(idname, **kwargs(name, text))
    for prop, value in props.items():
        setattr(operator, prop, value)
    return operator


def register() -> None:
    global _collection
    if _collection is None:
        import bpy.utils.previews  # lazily available submodule
        _collection = bpy.utils.previews.new()
    for name in available():
        if name in _collection:
            continue
        try:
            _collection.load(name, icon_path(name), "IMAGE")
        except (RuntimeError, TypeError):
            continue


def unregister() -> None:
    global _collection
    if _collection is not None:
        import bpy.utils.previews
        bpy.utils.previews.remove(_collection)
        _collection = None